package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.Vector _jspx_dependants;

  private org.glassfish.jsp.api.ResourceInjector _jspx_resourceInjector;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;

    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;
      _jspx_resourceInjector = (org.glassfish.jsp.api.ResourceInjector) application.getAttribute("com.sun.appserv.jsp.resource.injector");

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE HTML>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>Book Donation</title>\n");
      out.write("<!-- Bootstrap -->\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel='stylesheet' type='text/css' />\n");
      out.write("<link href=\"css/bootstrap.css\" rel='stylesheet' type='text/css' />\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>\n");
      out.write(" <!--[if lt IE 9]>\n");
      out.write("     <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\n");
      out.write("     <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\n");
      out.write("<![endif]-->\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\n");
      out.write("<!-- start plugins -->\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"js/bootstrap.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script>\n");
      out.write("<!-- start slider -->\n");
      out.write("<link href=\"css/slider.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\n");
      out.write("<script type=\"text/javascript\" src=\"js/modernizr.custom.28468.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.cslider.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t$(function() {\n");
      out.write("\n");
      out.write("\t\t\t\t$('#da-slider').cslider({\n");
      out.write("\t\t\t\t\tautoplay : true,\n");
      out.write("\t\t\t\t\tbgincrement : 450\n");
      out.write("\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t});\n");
      out.write("\t\t</script>\n");
      out.write("<!-- Owl Carousel Assets -->\n");
      out.write("<link href=\"css/owl.carousel.css\" rel=\"stylesheet\">\n");
      out.write("<script src=\"js/owl.carousel.js\"></script>\n");
      out.write("\t\t<script>\n");
      out.write("\t\t\t$(document).ready(function() {\n");
      out.write("\n");
      out.write("\t\t\t\t$(\"#owl-demo\").owlCarousel({\n");
      out.write("\t\t\t\t\titems : 4,\n");
      out.write("\t\t\t\t\tlazyLoad : true,\n");
      out.write("\t\t\t\t\tautoPlay : true,\n");
      out.write("\t\t\t\t\tnavigation : true,\n");
      out.write("\t\t\t\t\tnavigationText : [\"\", \"\"],\n");
      out.write("\t\t\t\t\trewindNav : false,\n");
      out.write("\t\t\t\t\tscrollPerPage : false,\n");
      out.write("\t\t\t\t\tpagination : false,\n");
      out.write("\t\t\t\t\tpaginationNumbers : false,\n");
      out.write("\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t});\n");
      out.write("\t\t</script>\n");
      out.write("\t\t<!-- //Owl Carousel Assets -->\n");
      out.write("<!----font-Awesome----->\n");
      out.write("   \t<link rel=\"stylesheet\" href=\"fonts/css/font-awesome.min.css\">\n");
      out.write("<!----font-Awesome----->\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"header_bg\">\n");
      out.write("<div class=\"container\">\n");
      out.write("\t<div class=\"row header\">\n");
      out.write("\t\t<div class=\"logo navbar-left\">\n");
      out.write("\t\t\t<h1><a href=\"index.jsp\">Donate A Book</a></h1>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"clearfix\"></div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("<div class=\"container\">\n");
      out.write("\t<div class=\"row h_menu\">\n");
      out.write("\t\t<nav class=\"navbar navbar-default navbar-left\" role=\"navigation\">\n");
      out.write("\t\t    <!-- Brand and toggle get grouped for better mobile display -->\n");
      out.write("\t\t    <div class=\"navbar-header\">\n");
      out.write("\t\t      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\n");
      out.write("\t\t        <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("\t\t        <span class=\"icon-bar\"></span>\n");
      out.write("\t\t        <span class=\"icon-bar\"></span>\n");
      out.write("\t\t        <span class=\"icon-bar\"></span>\n");
      out.write("\t\t      </button>\n");
      out.write("\t\t    </div>\n");
      out.write("\t\t    <!-- Collect the nav links, forms, and other content for toggling -->\n");
      out.write("\t\t    <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\n");
      out.write("\t\t      <ul class=\"nav navbar-nav\">\n");
      out.write("\t\t        <li class=\"active\"><a href=\"index.jsp\">Home</a></li>\n");
      out.write("\t\t        <li><a href=\"about.jsp\">About</a></li>\n");
      out.write("\t\t        <li><a href=\"test.jsp\">Donate</a></li>\n");
      out.write("\t\t        <li><a href=\"signup.jsp\">SignUp</a></li>\n");
      out.write("                        <li><a href=\"login.jsp\">Login</a></li>\n");
      out.write("\t\t\t<li><a href=\"search_book.jsp\">Receive</a></li>\n");
      out.write("                        <li><a href=\"contact.jsp\">Contact</a></li>\n");
      out.write("\t\t      </ul>\n");
      out.write("\t\t    </div><!-- /.navbar-collapse -->\n");
      out.write("\t\t    <!-- start soc_icons -->\n");
      out.write("\t\t</nav>\n");
      out.write("\t\t\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<div class=\"slider_bg\"><!-- start slider -->\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<div id=\"da-slider\" class=\"da-slider text-center\">\n");
      out.write("\t\t\t<div class=\"da-slide\">\n");
      out.write("\t\t\t\t<h2 style=\"color:#FFFFFF; text-shadow:1px 1px 2px #000000\">Spread a Smile</h2>\n");
      out.write("\t\t\t\t<p style=\"color:#FFFFFF; text-shadow:1px 1px 2px #000000\">Lorem Ipsum is simply dummy text of the printing and typesetting industry.<span class=\"hide_text\"> Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</span></p>\n");
      out.write("\t\t\t\t<!-- <h3 class=\"da-link\"><a href=\"single-page.html\" class=\"fa-btn btn-1 btn-1e\">view more</a></h3> -->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"da-slide\">\n");
      out.write("\t\t\t\t<h2 style=\"color:#FFFFFF; text-shadow:1px 1px 2px #000000\">Contribute For Change</h2>\n");
      out.write("\t\t\t\t<p style=\"color:#FFFFFF; text-shadow:1px 1px 2px #000000\">Lorem Ipsum is simply dummy text of the printing and typesetting industry.<span class=\"hide_text\">Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</span></p>\n");
      out.write("\t\t\t\t<!-- <h3 class=\"da-link\"><a href=\"single-page.html\" class=\"fa-btn btn-1 btn-1e\">view more</a></h3> -->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"da-slide\">\n");
      out.write("\t\t\t\t<h2 style=\"color:#FFFFFF; text-shadow:1px 1px 2px #000000\">Spread a Smile</h2>\n");
      out.write("\t\t\t\t<p style=\"color:#FFFFFF; text-shadow:1px 1px 2px #000000\">Lorem Ipsum is simply dummy text of the printing and typesetting industry.<span class=\"hide_text\"> Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</span></p>\n");
      out.write("\t\t\t\t<!-- <h3 class=\"da-link\"><a href=\"single-page.html\" class=\"fa-btn btn-1 btn-1e\">view more</a></h3> -->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"da-slide\">\n");
      out.write("\t\t\t\t<h2 style=\"color:#FFFFFF; text-shadow:1px 1px 2px #000000\">Contribute for change</h2>\n");
      out.write("\t\t\t\t<p style=\"color:#FFFFFF; text-shadow:1px 1px 2px #000000\">Lorem Ipsum is simply dummy text of the printing and typesetting industry.<span class=\"hide_text\"> Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</span></p>\n");
      out.write("\t\t\t\t<!-- <h3 class=\"da-link\"><a href=\"single-page.html\" class=\"fa-btn btn-1 btn-1e\">view more</a></h3> -->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t   </div>\n");
      out.write("\t</div>\n");
      out.write("</div><!-- end slider -->\n");
      out.write("<div class=\"main_bg\"><!-- start main -->\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<div class=\"main row\">\n");
      out.write("\t\t\t<div class=\"col-md-4 images_1_of_4 text-center\">\n");
      out.write("\t\t\t\t<span class=\"bg\"><i class=\"fa fa-book\"></i></span>\n");
      out.write("\t\t\t\t<h4><a href=\"test1.jsp\">Books</a></h4>\n");
      out.write("\t\t\t\t<p class=\"para\">Studies have shown that giving wholeheartedly translates to personal happiness. In donating books you make other people happy as you make yourself happy. Who doesn’t want to be happy?</p>\n");
      out.write("\t\t\t\t<!-- <a href=\"single-page.html\" class=\"fa-btn btn-1 btn-1e\">read more</a> -->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-md-4 images_1_of_4 bg1 text-center\">\n");
      out.write("\t\t\t\t<span class=\"bg\"><i class=\"fa fa-female\"></i></span>\n");
      out.write("\t\t\t\t<h4><a href=\"#\">Uniform</a></h4>\n");
      out.write("\t\t\t\t<p class=\"para\">Thrift stores run by charitable organizations typically provide the only way the homeless and other disadvantaged people can afford clothes.</p>\n");
      out.write("\t\t\t\t<!-- <a href=\"single-page.html\" class=\"fa-btn btn-1 btn-1e\">read more</a> -->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-md-4 images_1_of_4 bg1 text-center\">\n");
      out.write("\t\t\t\t<span class=\"bg\"><i class=\"fa fa-cog\"></i></span>\n");
      out.write("\t\t\t\t<h4><a href=\"#\">Bags</a></h4>\n");
      out.write("\t\t\t\t<p class=\"para\">Donation centers get a surplus of school supplies at the beginning of every school year, but in the middle of the year, supplies run low. Pencils become stubs, math notebooks are on their last pages and backpack seams rip.</p>\n");
      out.write("\t\t\t\t<!-- <a href=\"single-page.html\" class=\"fa-btn btn-1 btn-1e\">read more</a> -->\n");
      out.write("\t\t\t</div>\t\t\n");
      out.write("\t\t\t<!--<div class=\"col-md-3 images_1_of_4 bg1 text-center\">\n");
      out.write("\t\t\t\t<span class=\"bg\"><i class=\"fa fa-shield\"></i> </span>\n");
      out.write("\t\t\t\t<h4><a href=\"#\">Donate</a></h4>\n");
      out.write("\t\t\t\t<p class=\"para\">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>\n");
      out.write("\t\t\t\t<a href=\"single-page.html\" class=\"fa-btn btn-1 btn-1e\">read more</a>\n");
      out.write("\t\t\t</div>-->\t\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div><!-- end main -->\n");
      out.write("<div class=\"main_btm\"><!-- start main_btm -->\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<div class=\"main row\">\n");
      out.write("\t\t\t<div class=\"col-md-6 content_left\">\n");
      out.write("\t\t\t\t<img src=\"images/pic1.jpg\" alt=\"\" class=\"img-responsive\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-md-6 content_right\">\n");
      out.write("\t\t\t\t<h4>Literacy For Youth</h4>\n");
      out.write("\t\t\t\t<p class=\"para\">India has rolled-out the Right to Education Act, but is yet to witness its complete and proper implementation.<br>\n");
      out.write("\n");
      out.write("Below are some facts on India’s standing on the literacy chart.<br>\n");
      out.write("\n");
      out.write("1.India is home of largest population of illiterate adults in world – 287 million, amounting to 37% of the global total.<br>\n");
      out.write("\n");
      out.write("2.47.78 % out of school  children are girls. In the next census they will be calculated as illiterate women, which would then have a ripple effect on the education of their children.<br>\n");
      out.write("\n");
      out.write("3.Bihar, Jharkhand and Uttar Pradesh are amongst the bottom five states in terms of literacy of Dalits.<br>\n");
      out.write("\n");
      out.write("4.India’s literacy rate has increased six times since the end of the British rule — from 12% to 74% in 2011, yet, India has the world’s largest population of illiterates.<br>\n");
      out.write("\n");
      out.write("5.The literacy rate of female Dalits in Bihar is 38.5% in 2011.  It is far behind India’s progress trend. It is still 30 years behind the India’s national literacy Rate which was 43.7 in 1981.<br>\n");
      out.write("\n");
      out.write("6.60 lakh children in India are still out-of-school<br>\n");
      out.write("\n");
      out.write("7.92% government schools are yet to fully implement the RTE Act.<br>\n");
      out.write("\n");
      out.write("8.India is ranked 123rd out of 135 countries in female literacy rate.<br>\n");
      out.write("\n");
      out.write("9.In the South Asian region, India ranks fourth, behind Sri Lanka with a female-male ratio of 0.97 and Bangladesh with a female-male ratio of 0.85.<br>\n");
      out.write("\n");
      out.write("10.The percentage of women to the total number of school teachers has gone up from 29.3% in 1991 to 47.16% in 2013-14.</p>\n");
      out.write("\t\t\t\t<!-- <a href=\"single-page.html\" class=\"fa-btn btn-1 btn-1e\">read more</a> -->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\t\t<!----start-img-cursual---->\n");
      out.write("\t\t\t\t\t<!--<div id=\"owl-demo\" class=\"owl-carousel text-center\">\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cau_left\">\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"lazyOwl\" data-src=\"images/c1.jpg\" alt=\"Lazy Owl Image\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cau_left\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4><a href=\"#\">vehicula diam</a></h4>\n");
      out.write("\t\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t\tLorem ipsum dolor amet,consectetur adipisicing elit, sed do eiusmod tempor incididunt dolore magna aliqua.\n");
      out.write("\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cau_left\">\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"lazyOwl\" data-src=\"images/c2.jpg\" alt=\"Lazy Owl Image\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cau_left\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4><a href=\"#\">Morbi nunc</a></h4>\n");
      out.write("\t\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t\tSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium,\n");
      out.write("\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cau_left\">\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"lazyOwl\" data-src=\"images/c3.jpg\" alt=\"Lazy Owl Image\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cau_left\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4><a href=\"#\">Lorem ipsum</a></h4>\n");
      out.write("\t\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t\tOn the other hand, we denounce with righteous indignation and dislike men who are so beguiled  pleasure of the moment,\n");
      out.write("\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cau_left\">\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"lazyOwl\" data-src=\"images/c4.jpg\" alt=\"Lazy Owl Image\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cau_left\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4><a href=\"#\">Sed faucibus</a></h4>\n");
      out.write("\t\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t\tLorem ipsum dolor amet,consectetur adipisicing elit, sed do eiusmod tempor incididunt dolore magna aliqua.\n");
      out.write("\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cau_left\">\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"lazyOwl\" data-src=\"images/c2.jpg\" alt=\"Lazy Owl Image\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cau_left\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4><a href=\"#\">Lorem ipsum</a></h4>\n");
      out.write("\t\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t\tSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium,\n");
      out.write("\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cau_left\">\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"lazyOwl\" data-src=\"images/c3.jpg\" alt=\"Lazy Owl Image\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cau_left\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4><a href=\"#\">Lorem ipsum</a></h4>\n");
      out.write("\t\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t\tOn the other hand, we denounce with righteous indignation and dislike men who are so beguiled  pleasure of the moment,\n");
      out.write("\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cau_left\">\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"lazyOwl\" data-src=\"images/c4.jpg\" alt=\"Lazy Owl Image\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cau_left\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4><a href=\"#\">vehicula diam</a></h4>\n");
      out.write("\t\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t\tSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium,\n");
      out.write("\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!--<div class=\"item\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cau_left\">\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"lazyOwl\" data-src=\"images/c1.jpg\" alt=\"Lazy Owl Image\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cau_left\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4><a href=\"#\">Lorem ipsum</a></h4>\n");
      out.write("\t\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t\tOn the other hand, we denounce with righteous indignation and dislike men who are so beguiled  pleasure of the moment,\n");
      out.write("\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cau_left\">\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"lazyOwl\" data-src=\"images/c2.jpg\" alt=\"Lazy Owl Image\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cau_left\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4><a href=\"#\">Lorem ipsum</a></h4>\n");
      out.write("\t\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t\tLorem ipsum dolor amet,consectetur adipisicing elit, sed do eiusmod tempor incididunt dolore magna aliqua.\n");
      out.write("\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cau_left\">\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"lazyOwl\" data-src=\"images/c3.jpg\" alt=\"Lazy Owl Image\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cau_left\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4><a href=\"#\">vehicula diam</a></h4>\n");
      out.write("\t\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t\tSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium,\n");
      out.write("\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cau_left\">\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"lazyOwl\" data-src=\"images/c1.jpg\" alt=\"Lazy Owl Image\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cau_left\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4><a href=\"#\">Lorem ipsum</a></h4>\n");
      out.write("\t\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t\tOn the other hand, we denounce with righteous indignation and dislike men who are so beguiled  pleasure of the moment,\n");
      out.write("\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cau_left\">\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"lazyOwl\" data-src=\"images/c4.jpg\" alt=\"Lazy Owl Image\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cau_left\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4><a href=\"#\">Morbi nunc</a></h4>\n");
      out.write("\t\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t\tSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium,\n");
      out.write("\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>-->\n");
      out.write("\t\t\t\t\t<!----//End-img-cursual---->\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<div class=\"footer_bg\"><!-- start footer -->\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<div class=\"row  footer\">\n");
      out.write("\t\t\t<div class=\"copy text-center\">\n");
      out.write("\t\t\t\t<p class=\"link\"><span>&#169; All rights reserved | Design by&nbsp;<a href=\"http://www.School.com/\">Donate A Book</a></span></p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!--\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <form>\n");
      out.write("            THIS IS THE FIRST PAGE\n");
      out.write("            <a href=\"test.jsp\">DONATE BOOKS</a><br>\n");
      out.write("            <a href=\"signup.jsp\">SIGN-UP</a><br>\n");
      out.write("            <a href=\"login.jsp\">LOGIN</a><br>\n");
      out.write("            <a href=\"buy_books.jsp\">GET BOOKS</a>\n");
      out.write("            \n");
      out.write("            </form>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("-->");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
